// Daily reminders for the Deen tab: Quran verses and hadith, each with a few short lessons.
// Quran meanings are in plain modern English rather than a word-for-word translation; the Arabic
// text lives in quran-arabic.js (generated by scripts/fetch-quran-arabic.js).
const REFLECTION_CATEGORIES = [
  ['patience', 'Patience'],
  ['hope', 'Hard times'],
  ['gratitude', 'Gratitude'],
  ['mercy', 'Forgiveness'],
  ['prayer', 'Prayer & dua'],
  ['trust', 'Trust in Allah'],
  ['dhikr', 'Remembrance'],
  ['character', 'Character'],
  ['family', 'Family & others'],
  ['knowledge', 'Knowledge'],
  ['charity', 'Charity'],
];

const REFLECTIONS = [
  // ---------- Quran ----------
  {
    id: 'q94-5', type: 'quran', verses: '94:5-6', surah: 'Ash-Sharh', cats: ['hope', 'patience'],
    text: 'So truly, with hardship comes ease. Truly, with hardship comes ease.',
    lessons: [
      'Ease comes with the hardship, not only after it. Look for the openings Allah gives you even in a hard stretch.',
      'It is said twice to reassure you. Early scholars noted that one hardship is paired with more than one ease.',
      'Whatever you are going through today is not the end of your story.',
    ],
  },
  {
    id: 'q2-286', type: 'quran', verses: '2:286', surah: 'Al-Baqarah', cats: ['hope', 'mercy', 'prayer'],
    text: 'Allah does not burden a soul beyond what it can bear. Each soul gets the good it has earned and bears the wrong it has done. “Our Lord, do not hold us to account if we forget or make a mistake. Our Lord, do not place on us a burden like the one You placed on those before us. Our Lord, do not load us with more than we have strength to bear. Pardon us, forgive us and have mercy on us. You are our Protector, so help us against those who deny the truth.”',
    lessons: [
      'What is on your plate today is within what you were made able to carry, even if it doesn’t feel that way.',
      'You answer for your own choices, not for everything that happens around you.',
      'The verse ends with a dua about forgetting and mistakes. Allah Himself taught us to ask for this, so ask for it.',
    ],
  },
  {
    id: 'q2-153', type: 'quran', verses: '2:153', surah: 'Al-Baqarah', cats: ['patience', 'prayer'],
    text: 'O you who believe, seek help through patience and prayer. Truly, Allah is with those who are patient.',
    lessons: [
      'Patience and prayer are things you actively use, not just a situation you wait out.',
      'When a problem feels too big, turn to salah before anything else.',
      'Allah’s company is promised to the patient, so you are never going through it alone.',
    ],
  },
  {
    id: 'q2-155', type: 'quran', verses: '2:155-156', surah: 'Al-Baqarah', cats: ['patience', 'hope'],
    text: 'We will certainly test you with some fear and hunger, and loss of wealth, lives and crops. But give good news to those who are patient: those who, when disaster strikes them, say, “We belong to Allah, and to Him we will return.”',
    lessons: [
      'Tests are a normal part of life, not a sign that Allah has abandoned you.',
      '“Inna lillahi wa inna ilayhi raji‘un” reminds you that everything you have is on loan from Allah.',
      'The good news goes to the patient. How you respond matters more than what happened.',
    ],
  },
  {
    id: 'q39-10', type: 'quran', verses: '39:10', surah: 'Az-Zumar', cats: ['patience'],
    text: 'Say, “O My servants who believe, be mindful of your Lord. Those who do good in this world will have good, and Allah’s earth is spacious. Only the patient will be given their reward in full, without measure.”',
    lessons: [
      'Most deeds have a known reward. The reward for patience is described as without measure.',
      'Good done in this world is never wasted, even when no one notices it.',
      '“Allah’s earth is spacious”: if one place or situation is suffocating you, there are other doors.',
    ],
  },
  {
    id: 'q12-87', type: 'quran', verses: '12:87', surah: 'Yusuf', cats: ['hope', 'trust'],
    text: '“My sons, go and search for Yusuf and his brother, and do not lose hope in Allah’s mercy. Only people who deny the truth lose hope in Allah’s mercy.”',
    lessons: [
      'Prophet Ya‘qub said this after losing two sons, years into his grief. He still expected good from Allah.',
      'His hope came with action: “go and search.” Keep trying while you keep hoping.',
      'Giving up on Allah’s mercy is treated as the opposite of faith, not as a normal reaction.',
    ],
  },
  {
    id: 'q65-3', type: 'quran', verses: '65:3', surah: 'At-Talaq', cats: ['trust'],
    text: '[Whoever is mindful of Allah, He will make a way out for them] and provide for them from where they never expected. Whoever puts their trust in Allah, He is enough for them. Allah always accomplishes His purpose. He has set a measure for everything.',
    lessons: [
      'Provision can come from places you never planned for. Your job, your plans and your contacts are not the only routes.',
      'Trusting Allah means doing your part, then not letting worry run your life.',
      'Everything has a measure and a time. A delay is not the same as a no.',
    ],
  },
  {
    id: 'q3-139', type: 'quran', verses: '3:139', surah: 'Al Imran', cats: ['hope'],
    text: 'Do not lose heart and do not grieve. You will have the upper hand if you are true believers.',
    lessons: [
      'This came after the painful setback at Uhud. A loss is not the final chapter.',
      'Faith is a source of strength when you feel knocked down.',
      'Feeling sad is human. The verse warns against letting it turn into giving up.',
    ],
  },
  {
    id: 'q13-28', type: 'quran', verses: '13:28', surah: 'Ar-Ra‘d', cats: ['dhikr', 'hope'],
    text: 'Those who believe and whose hearts find peace in the remembrance of Allah. Truly, it is in the remembrance of Allah that hearts find peace.',
    lessons: [
      'Restlessness often comes from looking for peace in things that can’t give it.',
      'A few minutes of dhikr is a real remedy when your mind won’t settle.',
      'Fit remembrance into moments you already have: walking, waiting, before sleep.',
    ],
  },
  {
    id: 'q2-152', type: 'quran', verses: '2:152', surah: 'Al-Baqarah', cats: ['dhikr', 'gratitude'],
    text: 'So remember Me, and I will remember you. Be grateful to Me, and do not be ungrateful.',
    lessons: [
      'When you remember Allah, the Lord of everything remembers you.',
      'Remembrance and gratitude go together. Both keep your heart awake to Allah.',
      'Ingratitude isn’t only in words. It is also forgetting where your blessings come from.',
    ],
  },
  {
    id: 'q14-7', type: 'quran', verses: '14:7', surah: 'Ibrahim', cats: ['gratitude'],
    text: 'And remember when your Lord declared, “If you are grateful, I will surely give you more. But if you are ungrateful, My punishment is severe.”',
    lessons: [
      'Gratitude brings increase: more blessings, and more contentment with what you have.',
      'Gratitude is a habit you can build. Try naming three specific blessings today.',
      'Using a blessing in a way Allah loves is part of being grateful for it.',
    ],
  },
  {
    id: 'q16-18', type: 'quran', verses: '16:18', surah: 'An-Nahl', cats: ['gratitude', 'mercy'],
    text: 'If you tried to count Allah’s blessings, you could never number them. Truly, Allah is Forgiving, Most Merciful.',
    lessons: [
      'The biggest blessings are the ones we stop noticing: breathing, sight, safety, people who care about us.',
      'Even our thanks falls short of what we’ve been given, and Allah is forgiving about that.',
      'Thank Allah today for one ordinary thing you usually take for granted.',
    ],
  },
  {
    id: 'q55-13', type: 'quran', verses: '55:13', surah: 'Ar-Rahman', cats: ['gratitude'],
    text: 'So which of your Lord’s blessings will you deny?',
    lessons: [
      'This question is repeated 31 times in Surah Ar-Rahman, each time after blessings are described.',
      'It is addressed to both humans and jinn, calling everyone to stop and acknowledge what they have.',
      'Denying a blessing can be silent: complaining as if you were never given anything.',
    ],
  },
  {
    id: 'q39-53', type: 'quran', verses: '39:53', surah: 'Az-Zumar', cats: ['mercy', 'hope'],
    text: 'Say, “O My servants who have wronged themselves, do not lose hope in Allah’s mercy. Truly, Allah forgives all sins. He is the Forgiving, the Most Merciful.”',
    lessons: [
      'No sin is too big to come back from when you turn back to Allah sincerely.',
      'Even those who wronged themselves are called “My servants.” You still belong to Him.',
      'Despair is a trap that keeps people from returning. Don’t let past mistakes stop your next good step.',
    ],
  },
  {
    id: 'q6-54', type: 'quran', verses: '6:54', surah: 'Al-An‘am', cats: ['mercy'],
    text: 'When those who believe in Our verses come to you, say, “Peace be upon you. Your Lord has taken it upon Himself to be merciful. Whoever of you does wrong out of ignorance, then repents afterwards and puts things right, He is Forgiving, Most Merciful.”',
    lessons: [
      'Allah has made mercy a promise upon Himself.',
      'Real repentance has two parts: turning back to Allah and fixing what you can.',
      'Greet people who come to you with peace, especially those who are trying to change.',
    ],
  },
  {
    id: 'q3-133', type: 'quran', verses: '3:133-134', surah: 'Al Imran', cats: ['character', 'mercy', 'charity'],
    text: 'Hurry towards forgiveness from your Lord and a Garden as wide as the heavens and the earth, prepared for the mindful: those who give in good times and bad, who hold back their anger and pardon people. Allah loves those who do good.',
    lessons: [
      'Holding back anger and forgiving people are named as qualities of the people of Paradise.',
      'Giving isn’t only for when money is easy. A little given in hard times counts.',
      '“Hurry”: don’t put off asking for forgiveness or doing good.',
    ],
  },
  {
    id: 'q24-22', type: 'quran', verses: '24:22', surah: 'An-Nur', cats: ['mercy', 'character', 'family'],
    text: 'Those of you who are well off and have means should not swear to stop giving to relatives, the poor and those who emigrated for Allah’s cause. Let them pardon and overlook. Don’t you love for Allah to forgive you? Allah is Forgiving, Most Merciful.',
    lessons: [
      'It was revealed about Abu Bakr, who swore to stop supporting a relative who had helped spread slander about his daughter Aisha. After hearing it, he started supporting him again.',
      'Forgiving others is tied to hoping that Allah forgives you.',
      'Pardon means letting it go. Overlook means not bringing it up again.',
    ],
  },
  {
    id: 'q2-186', type: 'quran', verses: '2:186', surah: 'Al-Baqarah', cats: ['prayer', 'hope'],
    text: 'When My servants ask you about Me, I am near. I answer the call of the one who calls on Me. So let them respond to Me and believe in Me, so that they may be guided.',
    lessons: [
      'Other questions in the Quran are answered with “Say…”. Here Allah answers directly: “I am near.”',
      'You don’t need anyone in between. Talk to Allah yourself, in your own words.',
      'Responding to Him through obedience is part of having your duas answered.',
    ],
  },
  {
    id: 'q40-60', type: 'quran', verses: '40:60', surah: 'Ghafir', cats: ['prayer'],
    text: 'Your Lord says, “Call on Me and I will answer you. Those who are too proud to worship Me will enter Hell, humbled.”',
    lessons: [
      'Asking Allah is itself worship, and He has promised to answer.',
      'Not asking out of pride is condemned. Ask for big things and small things.',
      'An answer can be what you asked for, something better saved for later, or harm kept away from you.',
    ],
  },
  {
    id: 'q2-201', type: 'quran', verses: '2:201', surah: 'Al-Baqarah', cats: ['prayer'],
    text: 'And there are those who say, “Our Lord, give us good in this world and good in the Hereafter, and protect us from the punishment of the Fire.”',
    lessons: [
      'Anas said this was the dua the Prophet ﷺ made most often (Bukhari 6389).',
      'It asks for balance: good in this life and the next, not one at the cost of the other.',
      'It is short and complete. Make it part of your daily duas.',
    ],
  },
  {
    id: 'q20-114', type: 'quran', verses: '20:114', surah: 'Taha', cats: ['knowledge', 'prayer'],
    text: 'Exalted is Allah, the True King. Do not rush to recite the Quran before its revelation to you is complete, and say, “My Lord, increase me in knowledge.”',
    lessons: [
      'The Prophet ﷺ was told to ask for more of one thing: knowledge.',
      'Learning takes patience. Don’t rush past understanding.',
      'Say “Rabbi zidni ‘ilma” before you study or read.',
    ],
  },
  {
    id: 'q96-1', type: 'quran', verses: '96:1-5', surah: 'Al-‘Alaq', cats: ['knowledge'],
    text: 'Read in the name of your Lord who created, created humans from a clinging clot. Read, for your Lord is the Most Generous, who taught by the pen, taught humans what they did not know.',
    lessons: [
      'The first words revealed to the Prophet ﷺ were a command to read.',
      'Learning “in the name of your Lord” gives study a purpose beyond grades or a job.',
      'Everything you know was taught to you by Allah, so knowledge should make you humble.',
    ],
  },
  {
    id: 'q29-45', type: 'quran', verses: '29:45', surah: 'Al-‘Ankabut', cats: ['prayer', 'dhikr'],
    text: 'Recite what has been revealed to you of the Book and establish prayer. Prayer keeps one away from shameful and wrong deeds, and the remembrance of Allah is even greater. Allah knows what you do.',
    lessons: [
      'Prayer done with presence changes how you act the rest of the day.',
      'If your prayer isn’t changing you, work on its quality, not just its count.',
      'Remembering Allah is the heart of every act of worship.',
    ],
  },
  {
    id: 'q23-1', type: 'quran', verses: '23:1-2', surah: 'Al-Mu’minun', cats: ['prayer'],
    text: 'The believers have truly succeeded: those who are humble and focused in their prayer.',
    lessons: [
      'Allah’s definition of success starts with how you pray.',
      'Khushu‘, focus and humility, grows when you slow down and understand what you are saying.',
      'Learn the meaning of one more phrase you say in salah this week.',
    ],
  },
  {
    id: 'q17-23', type: 'quran', verses: '17:23-24', surah: 'Al-Isra', cats: ['family'],
    text: 'Your Lord has decreed that you worship none but Him, and that you be good to your parents. If one or both of them reach old age while with you, do not say to them even “uff”, and do not push them away, but speak to them kindly and with respect. Lower to them the wing of humility out of mercy, and say, “My Lord, have mercy on them, as they raised me when I was small.”',
    lessons: [
      'Kindness to parents comes right after worshipping Allah alone.',
      'Even “uff”, a small sound of irritation, is ruled out when they are old.',
      'Make the dua “Rabbir-hamhuma kama rabbayani saghira” for them every day.',
    ],
  },
  {
    id: 'q31-14', type: 'quran', verses: '31:14', surah: 'Luqman', cats: ['family', 'gratitude'],
    text: 'We have commanded people to honour their parents. Their mothers carried them through hardship upon hardship, and weaning took two years. So be grateful to Me and to your parents. To Me is the final return.',
    lessons: [
      'A mother’s sacrifice is singled out, starting before you were even born.',
      'Thanking your parents is placed right beside thanking Allah.',
      'Call or visit your parents, or make dua for them if they have passed away.',
    ],
  },
  {
    id: 'q30-21', type: 'quran', verses: '30:21', surah: 'Ar-Rum', cats: ['family'],
    text: 'And among His signs is that He created spouses for you from among yourselves so that you may find comfort in them, and He placed love and mercy between you. Truly, in that are signs for people who reflect.',
    lessons: [
      'Marriage is meant to be a place of rest and comfort.',
      'Love and mercy both matter. Mercy keeps a relationship going when feelings dip.',
      'Good relationships are one of Allah’s signs. Reflect on them and be grateful.',
    ],
  },
  {
    id: 'q49-10', type: 'quran', verses: '49:10', surah: 'Al-Hujurat', cats: ['family', 'character'],
    text: 'The believers are one brotherhood, so make peace between your brothers, and be mindful of Allah so that you may receive mercy.',
    lessons: [
      'Fellow believers are family, wherever they are from.',
      'Don’t just stay out of arguments. Help people make up.',
      'Making peace between people is a way to receive Allah’s mercy.',
    ],
  },
  {
    id: 'q49-12', type: 'quran', verses: '49:12', surah: 'Al-Hujurat', cats: ['character'],
    text: 'O you who believe, avoid a lot of suspicion, for some suspicion is a sin. Do not spy on one another, and do not backbite one another. Would any of you like to eat the flesh of his dead brother? You would hate it. Be mindful of Allah. Allah is Ever-Accepting of repentance, Most Merciful.',
    lessons: [
      'Assume the best about people. A lot of suspicion is guesswork, and some of it is sin.',
      'Backbiting is compared to eating a dead brother’s flesh, something everyone finds disgusting.',
      'If you have slipped, the verse ends with hope: Allah accepts repentance.',
    ],
  },
  {
    id: 'q49-13', type: 'quran', verses: '49:13', surah: 'Al-Hujurat', cats: ['character', 'family'],
    text: 'O people, We created you from a male and a female and made you into nations and tribes so that you may get to know one another. The most honoured of you in Allah’s sight is the most mindful of Him. Allah is All-Knowing, All-Aware.',
    lessons: [
      'Differences in race and background exist so we can get to know each other, not to rank people.',
      'Honour with Allah comes from taqwa, not from wealth, looks or family name.',
      'Judge people by their character, the way Allah does.',
    ],
  },
  {
    id: 'q25-63', type: 'quran', verses: '25:63', surah: 'Al-Furqan', cats: ['character'],
    text: 'The servants of the Most Merciful are those who walk on the earth humbly, and when ignorant people speak to them rudely, they reply with words of peace.',
    lessons: [
      'Humility shows in small things, like how you walk and carry yourself.',
      'You don’t have to match rudeness. Answering calmly is a sign of strength.',
      'Walking away peacefully from a pointless argument is praised here.',
    ],
  },
  {
    id: 'q41-34', type: 'quran', verses: '41:34', surah: 'Fussilat', cats: ['character', 'patience'],
    text: 'Good and evil are not equal. Respond to evil with what is better, and the one who was your enemy will become like a close friend.',
    lessons: [
      'Answering harm with kindness can turn an enemy into a close friend.',
      'The next verse says only those who are patient reach this. It is hard, and it is worth it.',
      'Think of one tense relationship and one kind thing you could do in it.',
    ],
  },
  {
    id: 'q2-261', type: 'quran', verses: '2:261', surah: 'Al-Baqarah', cats: ['charity'],
    text: 'Those who spend their wealth in Allah’s way are like a grain that sprouts seven ears, with a hundred grains in each ear. Allah multiplies it for whom He wills. Allah is All-Encompassing, All-Knowing.',
    lessons: [
      'One grain becomes seven hundred. Small charity grows far beyond what you give.',
      '“Allah multiplies it for whom He wills”: sincerity can multiply it even more.',
      'Give regularly, even a little. Consistent giving adds up.',
    ],
  },
  {
    id: 'q3-92', type: 'quran', verses: '3:92', surah: 'Al Imran', cats: ['charity'],
    text: 'You will never reach true righteousness until you give from what you love. Whatever you give, Allah knows it well.',
    lessons: [
      'Real generosity is giving from what you value, not only from leftovers.',
      'When this was revealed, Abu Talha gave away his favourite garden, Bayruha’ (Bukhari).',
      'Allah knows every gift, even the ones nobody else sees.',
    ],
  },
  {
    id: 'q3-159', type: 'quran', verses: '3:159', surah: 'Al Imran', cats: ['character', 'trust'],
    text: 'It is by Allah’s mercy that you were gentle with them. Had you been harsh or hard-hearted, they would have scattered from around you. So pardon them, ask forgiveness for them and consult them in matters. Then once you have decided, put your trust in Allah. Allah loves those who put their trust in Him.',
    lessons: [
      'Gentleness keeps people close. Harshness pushes even good people away.',
      'Consulting others is a prophetic practice, not a weakness.',
      'Plan, decide, then trust Allah with the outcome.',
    ],
  },
  {
    id: 'q3-173', type: 'quran', verses: '3:173', surah: 'Al Imran', cats: ['trust'],
    text: 'Those who were told, “People have gathered against you, so fear them,” but it only increased their faith, and they said, “Allah is enough for us, and He is the best to rely on.”',
    lessons: [
      '“Hasbunallahu wa ni‘mal wakil” was said by Ibrahim when he was thrown into the fire, and by the Prophet ﷺ when he was threatened (Bukhari 4563).',
      'Pressure can increase faith instead of weakening it.',
      'Say it when you feel anxious about people or outcomes.',
    ],
  },
  {
    id: 'q9-51', type: 'quran', verses: '9:51', surah: 'At-Tawbah', cats: ['trust'],
    text: 'Say, “Nothing will happen to us except what Allah has written for us. He is our Protector.” And in Allah let the believers put their trust.',
    lessons: [
      'Nothing reaches you outside of what Allah has written. That brings calm.',
      'It says “for us”: what Allah writes for the believer is ultimately for their good.',
      'Do your part, then leave the results with your Protector.',
    ],
  },
  {
    id: 'q103-1', type: 'quran', verses: '103:1-3', surah: 'Al-‘Asr', cats: ['patience', 'character'],
    text: 'By time, surely people are in loss, except those who believe, do good deeds, and urge one another to the truth and urge one another to patience.',
    lessons: [
      'Time is your capital. A day spent without purpose is a loss.',
      'Four things save you from loss: faith, good deeds, encouraging truth and encouraging patience.',
      'Imam ash-Shafi‘i is reported to have said that if people reflected on this surah alone, it would be enough for them.',
    ],
  },
  {
    id: 'q50-16', type: 'quran', verses: '50:16', surah: 'Qaf', cats: ['dhikr', 'trust'],
    text: 'We created humans and We know what their souls whisper to them, and We are closer to them than their jugular vein.',
    lessons: [
      'Allah knows your private thoughts, even the ones you never say out loud.',
      'He is closer to you than your own jugular vein. You can always talk to Him.',
      'Pay attention to what your inner voice whispers, and steer it towards good.',
    ],
  },
  {
    id: 'q33-41', type: 'quran', verses: '33:41-42', surah: 'Al-Ahzab', cats: ['dhikr'],
    text: 'O you who believe, remember Allah often, and glorify Him morning and evening.',
    lessons: [
      'Remembrance isn’t limited to prayer times. “Often” means throughout your day.',
      'Morning and evening adhkar are a simple way to start and end the day with Allah.',
      'Use the tasbih counter below to build a daily dhikr habit.',
    ],
  },
  {
    id: 'q20-25', type: 'quran', verses: '20:25-28', surah: 'Taha', cats: ['prayer', 'hope'],
    text: '“My Lord, open my heart for me, make my task easy for me, and untie the knot from my tongue so they can understand what I say.”',
    lessons: [
      'Musa made this dua before facing Pharaoh, the hardest task of his life.',
      'It is a good dua before exams, presentations or difficult conversations.',
      'Musa was honest about his weakness in speaking and asked Allah to help with it.',
    ],
  },
  {
    id: 'q21-87', type: 'quran', verses: '21:87-88', surah: 'Al-Anbiya', cats: ['hope', 'prayer', 'mercy'],
    text: 'And remember Dhun-Nun (Yunus), when he left in anger, thinking We would not restrict him. Then he called out in the darkness, “There is no god but You. Glory be to You. I have truly been one of the wrongdoers.” So We answered him and saved him from distress. That is how We save the believers.',
    lessons: [
      'The Prophet ﷺ said no Muslim calls on Allah with this dua for anything without Allah answering him (Tirmidhi 3505).',
      'Yunus admitted his own mistake instead of blaming anyone else.',
      '“That is how We save the believers”: the same rescue is promised to us.',
    ],
  },
  {
    id: 'q53-39', type: 'quran', verses: '53:39', surah: 'An-Najm', cats: ['character'],
    text: 'And that each person will have only what they strive for.',
    lessons: [
      'Your effort is what counts with Allah, even when results don’t go your way.',
      'No one else’s deeds can stand in for yours. Take ownership of your own growth.',
      'Small, steady effort today is striving too.',
    ],
  },
  {
    id: 'q64-16', type: 'quran', verses: '64:16', surah: 'At-Taghabun', cats: ['charity', 'character'],
    text: 'So be mindful of Allah as much as you are able. Listen, obey and give, for that is better for you. Whoever is saved from their own greed, it is they who are successful.',
    lessons: [
      'Allah asks for what you are able to do, not perfection.',
      'Greed is named as the thing that holds people back from success.',
      'Giving in good ways benefits you before it benefits anyone else.',
    ],
  },
  {
    id: 'q3-190', type: 'quran', verses: '3:190-191', surah: 'Al Imran', cats: ['dhikr', 'knowledge'],
    text: 'In the creation of the heavens and the earth and the alternation of night and day are signs for people of understanding: those who remember Allah standing, sitting and lying on their sides, and reflect on the creation of the heavens and the earth. “Our Lord, You did not create all this without purpose. Glory be to You. Protect us from the punishment of the Fire.”',
    lessons: [
      'The Prophet ﷺ would recite these verses when he woke up at night to pray (Bukhari).',
      'Reflecting on the sky, nature and the cycle of day and night is a form of worship.',
      'Remember Allah in every position: standing, sitting and lying down.',
    ],
  },

  // ---------- Hadith ----------
  {
    id: 'h-bukhari-1', type: 'hadith', source: 'Sahih al-Bukhari 1', link: 'bukhari:1', narrator: 'Umar ibn al-Khattab', cats: ['character'],
    text: '“Actions are judged only by intentions, and every person will have only what they intended…”',
    lessons: [
      'The same action can be worship or nothing, depending on why you do it.',
      'Set a good intention for ordinary things like work, study, eating and sleep, and they become rewarded.',
      'Before you start something today, ask yourself who it is for.',
    ],
  },
  {
    id: 'h-bukhari-13', type: 'hadith', source: 'Sahih al-Bukhari 13', link: 'bukhari:13', narrator: 'Anas ibn Malik', cats: ['character', 'family'],
    text: '“None of you truly believes until he loves for his brother what he loves for himself.”',
    lessons: [
      'Faith shows in wanting good for others, not only for yourself.',
      'Be happy when others succeed, and let go of envy.',
      'Treat people the way you would want to be treated.',
    ],
  },
  {
    id: 'h-muslim-47', type: 'hadith', source: 'Sahih Muslim 47', link: 'muslim:47', narrator: 'Abu Hurairah', cats: ['character', 'family'],
    text: '“Whoever believes in Allah and the Last Day should say something good or stay silent. Whoever believes in Allah and the Last Day should honour their neighbour. Whoever believes in Allah and the Last Day should honour their guest.”',
    lessons: [
      'If what you are about to say isn’t good, silence is better.',
      'Neighbours have real rights over you.',
      'Welcoming guests warmly is part of faith, not just good manners.',
    ],
  },
  {
    id: 'h-bukhari-6114', type: 'hadith', source: 'Sahih al-Bukhari 6114', link: 'bukhari:6114', narrator: 'Abu Hurairah', cats: ['character', 'patience'],
    text: '“The strong person is not the one who can wrestle others down. The strong person is the one who controls himself when he is angry.”',
    lessons: [
      'Real strength is self-control, not winning arguments.',
      'When anger rises, pause. Sit down, stay quiet or make wudu.',
      'The moment you feel most provoked is when self-control counts most.',
    ],
  },
  {
    id: 'h-muslim-2564', type: 'hadith', source: 'Sahih Muslim 2564c', link: 'muslim:2564c', narrator: 'Abu Hurairah', cats: ['character'],
    text: '“Allah does not look at your appearance or your wealth. He looks at your hearts and your deeds.”',
    lessons: [
      'What matters to Allah is invisible to most people: your intentions and your actions.',
      'Don’t judge yourself or others by looks, money or followers.',
      'Put as much effort into your heart as you put into your appearance.',
    ],
  },
  {
    id: 'h-muslim-2999', type: 'hadith', source: 'Sahih Muslim 2999', link: 'muslim:2999', narrator: 'Suhayb', cats: ['gratitude', 'patience'],
    text: '“How amazing is the affair of the believer! All of it is good for him, and that is only for the believer. If something good happens to him, he is grateful, and that is good for him. If something bad happens to him, he is patient, and that is good for him.”',
    lessons: [
      'For a believer no situation is wasted. Good times and hard times can both earn reward.',
      'Gratitude in ease and patience in hardship go hand in hand.',
      'Ask yourself which one today calls for: gratitude or patience.',
    ],
  },
  {
    id: 'h-bukhari-6464', type: 'hadith', source: 'Sahih al-Bukhari 6464', link: 'bukhari:6464', narrator: 'Aisha', cats: ['character', 'prayer'],
    text: '“The deeds most loved by Allah are those done consistently, even if they are small.”',
    lessons: [
      'Small daily habits beat big bursts of effort that don’t last.',
      'Pick one small deed you can keep up every day, like two pages of Quran.',
      'This is the whole idea behind tracking habits: consistency over intensity.',
    ],
  },
  {
    id: 'h-tirmidhi-1956', type: 'hadith', source: 'Jami‘ at-Tirmidhi 1956', link: 'tirmidhi:1956', narrator: 'Abu Dharr', cats: ['charity', 'character'],
    text: '“Your smiling in the face of your brother is charity. Encouraging good and discouraging wrong is charity. Guiding someone who is lost is charity…”',
    lessons: [
      'Charity isn’t only money. A smile counts.',
      'Everyday kindness, like giving directions or helping someone out, is written as sadaqah.',
      'No one is too poor to give something.',
    ],
  },
  {
    id: 'h-muslim-2699', type: 'hadith', source: 'Sahih Muslim 2699', link: 'muslim:2699', narrator: 'Abu Hurairah', cats: ['knowledge', 'charity'],
    text: '“Whoever relieves a believer of a hardship of this world, Allah will relieve him of a hardship on the Day of Resurrection… Allah helps His servant as long as the servant helps his brother. Whoever takes a path seeking knowledge, Allah makes easy for him a path to Paradise.”',
    lessons: [
      'Helping people is a way of getting Allah’s help for yourself.',
      'Seeking knowledge, even one class or one book, is a path to Paradise.',
      'Think of someone whose burden you could lighten this week.',
    ],
  },
  {
    id: 'h-muslim-2588', type: 'hadith', source: 'Sahih Muslim 2588', link: 'muslim:2588', narrator: 'Abu Hurairah', cats: ['charity', 'mercy'],
    text: '“Charity does not decrease wealth. Allah only increases in honour the one who forgives, and no one humbles himself for Allah except that Allah raises him.”',
    lessons: [
      'Giving never really leaves you with less. Allah puts barakah in what remains.',
      'Forgiving people isn’t weakness. Allah raises your honour for it.',
      'Humility brings you higher, not lower.',
    ],
  },
  {
    id: 'h-abudawud-4811', type: 'hadith', source: 'Sunan Abi Dawud 4811', link: 'abudawud:4811', narrator: 'Abu Hurairah', cats: ['gratitude'],
    text: '“Whoever does not thank people has not thanked Allah.”',
    lessons: [
      'Thanking people is part of thanking Allah, since He sends good to you through them.',
      'Say thank you out loud to someone today, even for something small.',
      'Notice the people who make your day work: family, teachers, coworkers.',
    ],
  },
  {
    id: 'h-bukhari-5027', type: 'hadith', source: 'Sahih al-Bukhari 5027', link: 'bukhari:5027', narrator: 'Uthman ibn Affan', cats: ['knowledge'],
    text: '“The best of you are those who learn the Quran and teach it.”',
    lessons: [
      'Learning the Quran and passing it on is among the best things you can do.',
      'Teaching can be simple, like helping a younger sibling learn a surah.',
      'Keep learning at your own pace, a verse or a page at a time.',
    ],
  },
  {
    id: 'h-bukhari-69', type: 'hadith', source: 'Sahih al-Bukhari 69', link: 'bukhari:69', narrator: 'Anas ibn Malik', cats: ['character'],
    text: '“Make things easy and do not make them difficult. Give good news and do not drive people away.”',
    lessons: [
      'When helping people practise their faith, lead with ease and encouragement.',
      'Harshness can push people away from something good.',
      'Be the kind of person people feel comfortable coming back to.',
    ],
  },
  {
    id: 'h-tirmidhi-2344', type: 'hadith', source: 'Jami‘ at-Tirmidhi 2344', link: 'tirmidhi:2344', narrator: 'Umar ibn al-Khattab', cats: ['trust'],
    text: '“If you relied on Allah as He truly deserves, He would provide for you as He provides for the birds. They go out hungry in the morning and come back full in the evening.”',
    lessons: [
      'The birds don’t sit in their nests waiting. They go out, and Allah provides.',
      'Tawakkul means effort plus trust, not trust instead of effort.',
      'Worrying about provision doesn’t add to it. Work, then trust.',
    ],
  },
  {
    id: 'h-tirmidhi-2517', type: 'hadith', source: 'Jami‘ at-Tirmidhi 2517', link: 'tirmidhi:2517', narrator: 'Anas ibn Malik', cats: ['trust'],
    text: 'A man asked, “Should I tie my camel and trust in Allah, or leave it untied and trust in Allah?” The Prophet ﷺ said, “Tie it, and trust in Allah.”',
    lessons: [
      'Taking practical steps is part of trusting Allah, not the opposite of it.',
      'Study for the exam, lock the door, save your work, then leave the rest to Allah.',
      'Trusting Allah never means being careless.',
    ],
  },
  {
    id: 'h-bukhari-528', type: 'hadith', source: 'Sahih al-Bukhari 528', link: 'bukhari:528', narrator: 'Abu Hurairah', cats: ['prayer', 'mercy'],
    text: '“If there were a river at the door of one of you and he bathed in it five times a day, would any dirt be left on him?” They said, “No dirt would be left.” He said, “That is like the five prayers. Allah wipes away sins with them.”',
    lessons: [
      'Each prayer is a fresh start that washes away the small mistakes of the day.',
      'Missing a prayer means missing a chance to be cleansed.',
      'Treat salah as a break that refreshes you, not a task that interrupts you.',
    ],
  },
  {
    id: 'h-tirmidhi-3895', type: 'hadith', source: 'Jami‘ at-Tirmidhi 3895', link: 'tirmidhi:3895', narrator: 'Aisha', cats: ['family'],
    text: '“The best of you are those who are best to their families, and I am the best of you to my family.”',
    lessons: [
      'Character is tested most at home, where no one is watching.',
      'The Prophet ﷺ helped around the house and was gentle with his family.',
      'Be as kind at home as you are with friends and strangers.',
    ],
  },
  {
    id: 'h-bukhari-5971', type: 'hadith', source: 'Sahih al-Bukhari 5971', link: 'bukhari:5971', narrator: 'Abu Hurairah', cats: ['family'],
    text: 'A man asked, “Who most deserves my good company?” The Prophet ﷺ said, “Your mother.” He asked, “Then who?” He said, “Your mother.” He asked, “Then who?” He said, “Your mother.” He asked, “Then who?” He said, “Your father.”',
    lessons: [
      'Your mother is mentioned three times before your father.',
      'Good company means your time, patience and kind words, not just gifts.',
      'Honouring your father is still a duty. Both parents deserve your best.',
    ],
  },
  {
    id: 'h-bukhari-6412', type: 'hadith', source: 'Sahih al-Bukhari 6412', link: 'bukhari:6412', narrator: 'Ibn Abbas', cats: ['gratitude'],
    text: '“There are two blessings that many people lose out on: health and free time.”',
    lessons: [
      'Health and free time feel endless until they are gone.',
      'Use some free time today for something you will be glad about later.',
      'Thank Allah for your health by using it well.',
    ],
  },
  {
    id: 'h-bukhari-6416', type: 'hadith', source: 'Sahih al-Bukhari 6416', link: 'bukhari:6416', narrator: 'Ibn Umar', cats: ['character', 'hope'],
    text: 'The Messenger of Allah ﷺ took hold of my shoulder and said, “Be in this world as if you were a stranger or a traveller.”',
    lessons: [
      'A traveller enjoys the journey but never forgets where they are going.',
      'Don’t get so attached to this world that losing parts of it breaks you.',
      'Ibn Umar used to add: use your health before sickness, and your life before death.',
    ],
  },
  {
    id: 'h-bukhari-6116', type: 'hadith', source: 'Sahih al-Bukhari 6116', link: 'bukhari:6116', narrator: 'Abu Hurairah', cats: ['character', 'patience'],
    text: 'A man said to the Prophet ﷺ, “Advise me.” He said, “Do not get angry.” The man asked again several times, and each time he said, “Do not get angry.”',
    lessons: [
      'Anger is behind many regrets: harsh words, broken ties and bad decisions.',
      'Repeating the same advice shows how important it is.',
      'Notice what usually sets you off, and plan how you will respond next time.',
    ],
  },
  {
    id: 'h-tirmidhi-1987', type: 'hadith', source: 'Jami‘ at-Tirmidhi 1987', link: 'tirmidhi:1987', narrator: 'Abu Dharr', cats: ['character', 'mercy'],
    text: '“Be mindful of Allah wherever you are. Follow a bad deed with a good one and it will wipe it out. And treat people with good character.”',
    lessons: [
      'Taqwa isn’t only for the masjid. It goes with you everywhere.',
      'After a mistake, don’t spiral. Do something good straight away.',
      'Your relationship with Allah and your manners with people go together.',
    ],
  },
  {
    id: 'h-tirmidhi-1162', type: 'hadith', source: 'Jami‘ at-Tirmidhi 1162', link: 'tirmidhi:1162', narrator: 'Abu Hurairah', cats: ['character', 'family'],
    text: '“The believers with the most complete faith are those with the best character, and the best of you are those who are best to their wives.”',
    lessons: [
      'Good character is a measure of faith, not an optional extra.',
      'How someone treats their spouse shows their real character.',
      'Work on one trait this week, like patience, honesty or gentleness.',
    ],
  },
  {
    id: 'h-tirmidhi-2002', type: 'hadith', source: 'Jami‘ at-Tirmidhi 2002', link: 'tirmidhi:2002', narrator: 'Abu ad-Darda', cats: ['character'],
    text: '“Nothing will be heavier on the believer’s scale on the Day of Resurrection than good character…”',
    lessons: [
      'Good manners weigh more than people think.',
      'Small courtesies, like greeting people and speaking kindly, add up on your scale.',
      'Character can be improved, one habit at a time.',
    ],
  },
  {
    id: 'h-tirmidhi-2969', type: 'hadith', source: 'Jami‘ at-Tirmidhi 2969', link: 'tirmidhi:2969', narrator: 'An-Nu‘man ibn Bashir', cats: ['prayer'],
    text: '“Dua is worship.” Then he recited, “Your Lord says: Call on Me and I will answer you.” (40:60)',
    lessons: [
      'Every time you ask Allah for something, you are worshipping Him.',
      'Needing Allah isn’t something to hide. That need is what makes dua worship.',
      'Make dua for small everyday things too, not only emergencies.',
    ],
  },
  {
    id: 'h-bukhari-5641', type: 'hadith', source: 'Sahih al-Bukhari 5641', link: 'bukhari:5641', narrator: 'Abu Sa‘id and Abu Hurairah', cats: ['patience', 'hope'],
    text: '“No tiredness, illness, worry, sadness, harm or distress befalls a Muslim, not even a thorn that pricks him, except that Allah wipes away some of his sins because of it.”',
    lessons: [
      'Nothing you go through is wasted. Even small pains carry reward.',
      'Tiredness and stress can become a source of forgiveness when you are patient.',
      'This doesn’t mean looking for hardship, but it changes how you see it when it comes.',
    ],
  },
  {
    id: 'h-tirmidhi-2499', type: 'hadith', source: 'Jami‘ at-Tirmidhi 2499', link: 'tirmidhi:2499', narrator: 'Anas ibn Malik', cats: ['mercy'],
    text: '“Every child of Adam makes mistakes, and the best of those who make mistakes are those who repent.”',
    lessons: [
      'Making mistakes is human. What matters is what you do next.',
      'Repenting puts you among “the best”, even after a slip.',
      'Say “astaghfirullah” often. The Prophet ﷺ said it more than seventy times a day (Bukhari 6307).',
    ],
  },
  {
    id: 'h-muslim-2759', type: 'hadith', source: 'Sahih Muslim 2759a', link: 'muslim:2759a', narrator: 'Abu Musa al-Ash‘ari', cats: ['mercy', 'hope'],
    text: '“Allah stretches out His hand at night so that whoever sinned during the day may repent, and He stretches out His hand during the day so that whoever sinned at night may repent, until the sun rises from the west.”',
    lessons: [
      'The door to repentance is open every day and every night.',
      'There is no waiting period. You can turn back to Allah right now.',
      'The door stays open until the end of time, but none of us knows how much time we have.',
    ],
  },
  {
    id: 'h-bukhari-10', type: 'hadith', source: 'Sahih al-Bukhari 10', link: 'bukhari:10', narrator: 'Abdullah ibn ‘Amr', cats: ['character'],
    text: '“A Muslim is the one from whose tongue and hand other Muslims are safe…”',
    lessons: [
      'Your Islam shows in how safe people feel around you.',
      'The tongue is mentioned first. Words often hurt more than hands.',
      'This includes what you type: messages, comments and posts.',
    ],
  },
  {
    id: 'h-bukhari-7405', type: 'hadith', source: 'Sahih al-Bukhari 7405', link: 'bukhari:7405', narrator: 'Abu Hurairah', cats: ['dhikr', 'hope'],
    text: '“Allah says: I am as My servant thinks of Me, and I am with him when he remembers Me. If he remembers Me to himself, I remember him to Myself. If he remembers Me in a gathering, I remember him in a better gathering. If he comes a hand’s span closer to Me, I come an arm’s length closer to him. If he comes to Me walking, I come to him running.”',
    lessons: [
      'Think well of Allah. Expect His mercy and His help.',
      'When you remember Allah privately, He remembers you.',
      'Take one step towards Allah and He comes to you with far more.',
    ],
  },
  {
    id: 'h-tirmidhi-2317', type: 'hadith', source: 'Jami‘ at-Tirmidhi 2317', link: 'tirmidhi:2317', narrator: 'Abu Hurairah', cats: ['character'],
    text: '“Part of the excellence of a person’s Islam is leaving what does not concern him.”',
    lessons: [
      'Not every conversation, argument or bit of gossip needs you.',
      'Protecting your time and attention is part of good faith.',
      'Before scrolling or joining in, ask: does this concern me?',
    ],
  },
  {
    id: 'h-muslim-2594', type: 'hadith', source: 'Sahih Muslim 2594', link: 'muslim:2594', narrator: 'Aisha', cats: ['character', 'family'],
    text: '“Gentleness is not found in anything except that it makes it beautiful, and it is not removed from anything except that it makes it ugly.”',
    lessons: [
      'The same message lands better when it is said gently.',
      'Gentleness improves everything: advice, parenting and disagreements.',
      'Harshness can spoil even something that was right.',
    ],
  },
  {
    id: 'h-tirmidhi-1924', type: 'hadith', source: 'Jami‘ at-Tirmidhi 1924', link: 'tirmidhi:1924', narrator: 'Abdullah ibn ‘Amr', cats: ['mercy'],
    text: '“Those who show mercy will be shown mercy by the Most Merciful. Be merciful to those on earth, and the One above the heavens will be merciful to you.”',
    lessons: [
      'The mercy you show others comes back to you from Allah.',
      'Mercy includes animals, strangers and people who annoy you.',
      'When you need Allah’s mercy, show some to someone else.',
    ],
  },
  {
    id: 'h-bukhari-6446', type: 'hadith', source: 'Sahih al-Bukhari 6446', link: 'bukhari:6446', narrator: 'Abu Hurairah', cats: ['gratitude'],
    text: '“Richness is not having lots of possessions. Real richness is richness of the soul.”',
    lessons: [
      'Contentment makes you rich no matter how much you own.',
      'Chasing more rarely brings peace. Being satisfied does.',
      'Compare less, and thank more.',
    ],
  },
  {
    id: 'h-muslim-2963', type: 'hadith', source: 'Sahih Muslim 2963', link: 'muslim:2963', narrator: 'Abu Hurairah', cats: ['gratitude'],
    text: '“When one of you looks at someone who has been given more wealth or a better appearance than him, let him also look at someone who has been given less.”',
    lessons: [
      'Constantly comparing yourself with people who have more steals your gratitude.',
      'Remembering people with less keeps your own blessings in view.',
      'Social media mostly shows people “above” you. Balance it by remembering those below.',
    ],
  },
  {
    id: 'h-muslim-1631', type: 'hadith', source: 'Sahih Muslim 1631', link: 'muslim:1631', narrator: 'Abu Hurairah', cats: ['charity', 'knowledge'],
    text: '“When a person dies, their deeds come to an end except for three: ongoing charity, knowledge that benefits others, or a righteous child who prays for them.”',
    lessons: [
      'Some deeds keep earning reward long after you are gone.',
      'Ongoing charity includes things like wells, masjids, books and planting trees.',
      'Teaching something useful, or raising good children, is an investment that lasts.',
    ],
  },
  {
    id: 'h-tirmidhi-3375', type: 'hadith', source: 'Jami‘ at-Tirmidhi 3375', link: 'tirmidhi:3375', narrator: 'Abdullah ibn Busr', cats: ['dhikr'],
    text: 'A man said, “The laws of Islam have become too many for me, so tell me something I can hold on to.” The Prophet ﷺ said, “Keep your tongue moist with the remembrance of Allah.”',
    lessons: [
      'When everything feels like too much, start with dhikr. It is easy and always available.',
      '“Moist with remembrance” means constant and natural, not rare.',
      'Pick a phrase like “SubhanAllah” or “Alhamdulillah” and repeat it in idle moments.',
    ],
  },
  {
    id: 'h-bukhari-6406', type: 'hadith', source: 'Sahih al-Bukhari 6406', link: 'bukhari:6406', narrator: 'Abu Hurairah', cats: ['dhikr'],
    text: '“Two phrases are light on the tongue, heavy on the scale and beloved to the Most Merciful: SubhanAllahi wa bihamdihi, SubhanAllahil-‘Azim.”',
    lessons: [
      'Some of the heaviest deeds take only a few seconds.',
      'Say these two phrases a few times while you wait or walk.',
      'Imam al-Bukhari chose this hadith to close his whole collection.',
    ],
  },
  {
    id: 'h-tirmidhi-2516', type: 'hadith', source: 'Jami‘ at-Tirmidhi 2516', link: 'tirmidhi:2516', narrator: 'Ibn Abbas', cats: ['trust'],
    text: '“Be mindful of Allah and He will protect you. Be mindful of Allah and you will find Him in front of you. When you ask, ask Allah. When you seek help, seek help from Allah. Know that if the whole nation gathered to benefit you with something, they could only benefit you with what Allah has already written for you…”',
    lessons: [
      'Ibn Abbas was a young boy when the Prophet ﷺ taught him this. It is advice for every age.',
      'Guard Allah’s limits, and He guards you.',
      'People can only help or harm you within what Allah has already written.',
    ],
  },
  {
    id: 'h-bukhari-1283', type: 'hadith', source: 'Sahih al-Bukhari 1283', link: 'bukhari:1283', narrator: 'Anas ibn Malik', cats: ['patience'],
    text: 'The Prophet ﷺ passed by a woman crying at a grave and told her to fear Allah and be patient. She did not recognise him and told him to leave her alone. When she later came to him, he said, “Patience is at the first moment of the blow.”',
    lessons: [
      'The real test of patience is how you react in the very first moment.',
      'Grief is natural. Patience is holding on to faith while you feel it.',
      'The Prophet ﷺ answered her kindly, even after she spoke harshly to him.',
    ],
  },
  {
    id: 'h-bukhari-1469', type: 'hadith', source: 'Sahih al-Bukhari 1469', link: 'bukhari:1469', narrator: 'Abu Sa‘id al-Khudri', cats: ['patience'],
    text: '“…Whoever tries to be patient, Allah will make him patient. And no one has been given a gift better or greater than patience.”',
    lessons: [
      'Patience is a skill you grow by practising it.',
      'When you make the effort, Allah helps you with the rest.',
      'Of all the gifts a person can be given, patience is described as the best.',
    ],
  },
  {
    id: 'h-bukhari-6021', type: 'hadith', source: 'Sahih al-Bukhari 6021', link: 'bukhari:6021', narrator: 'Jabir ibn Abdullah', cats: ['charity'],
    text: '“Every act of kindness is charity.”',
    lessons: [
      'Kindness in any form counts as sadaqah.',
      'Holding a door, helping with homework and sharing food are all charity.',
      'You can give charity many times a day without spending any money.',
    ],
  },
  {
    id: 'h-muslim-2626', type: 'hadith', source: 'Sahih Muslim 2626', link: 'muslim:2626', narrator: 'Abu Dharr', cats: ['character', 'charity'],
    text: '“Do not think little of any good deed, even meeting your brother with a cheerful face.”',
    lessons: [
      'No good deed is too small to matter.',
      'A cheerful face can change someone’s whole day.',
      'Small deeds done sincerely may be what tips your scale.',
    ],
  },
  {
    id: 'h-bukhari-6014', type: 'hadith', source: 'Sahih al-Bukhari 6014', link: 'bukhari:6014', narrator: 'Aisha', cats: ['family'],
    text: '“Jibril kept urging me to treat neighbours well until I thought he would make them heirs.”',
    lessons: [
      'Neighbours’ rights were stressed so much that the Prophet ﷺ thought they might be given a share of inheritance.',
      'Greet your neighbours, check on them and share with them.',
      'Being a good neighbour also means not bothering them with noise or mess.',
    ],
  },
  {
    id: 'h-muslim-2734', type: 'hadith', source: 'Sahih Muslim 2734', link: 'muslim:2734', narrator: 'Anas ibn Malik', cats: ['gratitude'],
    text: '“Allah is pleased with a servant who eats a meal and praises Him for it, or drinks something and praises Him for it.”',
    lessons: [
      'Saying “Alhamdulillah” after eating earns Allah’s pleasure.',
      'The simplest daily routines can become worship.',
      'Don’t let a meal pass without noticing that it was a gift.',
    ],
  },
  {
    id: 'h-tirmidhi-2346', type: 'hadith', source: 'Jami‘ at-Tirmidhi 2346', link: 'tirmidhi:2346', narrator: 'Ubaydullah ibn Mihsan', cats: ['gratitude'],
    text: '“Whoever wakes up feeling safe in his home, healthy in his body, and has food for the day, it is as if he has been given the whole world.”',
    lessons: [
      'Safety, health and today’s food are already a lot.',
      'Many people in the world are missing at least one of these three.',
      'Each morning, check whether you have all three, then say Alhamdulillah.',
    ],
  },
  {
    id: 'h-muslim-1893', type: 'hadith', source: 'Sahih Muslim 1893', link: 'muslim:1893', narrator: 'Abu Mas‘ud al-Ansari', cats: ['knowledge', 'charity'],
    text: '“Whoever guides someone to something good will have a reward like the one who does it.”',
    lessons: [
      'Sharing a good idea, a reminder or a useful lesson earns you reward too.',
      'You lose none of your own reward when others benefit from your advice.',
      'Pass on one beneficial thing you learned today.',
    ],
  },
  {
    id: 'h-abudawud-1522', type: 'hadith', source: 'Sunan Abi Dawud 1522', link: 'abudawud:1522', narrator: 'Mu‘adh ibn Jabal', cats: ['prayer', 'dhikr', 'gratitude'],
    text: 'The Prophet ﷺ took Mu‘adh by the hand and said, “Mu‘adh, by Allah, I love you. Never leave off saying after every prayer: O Allah, help me to remember You, to thank You and to worship You well.”',
    lessons: [
      'The Prophet ﷺ began his advice by telling Mu‘adh he loved him. Advice lands better with love.',
      'Remembering Allah, thanking Him and worshipping Him well all need His help.',
      '“Allahumma a‘inni ‘ala dhikrika wa shukrika wa husni ‘ibadatik” is short enough to say after every salah.',
    ],
  },
];
